name: CI

on:
  workflow_dispatch:
  
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
    
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.USERNAME }}  
          password: ${{ secrets.PASSWORD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          tags: |
            guilhermebrumatti/desafio1:v1
            guilhermebrumatti/desafio1:latest
            
      - name: Docker Build Tag Publish      
        uses: bitovi/github-actions-docker-publish@v1.0.7
        with:
          image_tag: latest
          repo_name: guilhermebrumatti/desafio1
          docker_username: ${{ secrets.USERNAME }}
          docker_password: ${{ secrets.PASSWORD }}
