name: CI
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Loga no GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Builda a imagem do python e sobe no Packages do GitHub
        run: |
               docker build . --tag ghcr.io/guilhermebrumatti/python_image:latest
               docker run ghcr.io/guilhermebrumatti/python_image:latest
               docker push ghcr.io/guilhermebrumatti/python_image:latest
